from __future__ import annotations

from typing import Any, Protocol

from .models import EventRecord, QueueDelivery, WorkflowState


class RuntimeStore(Protocol):
    def create_workflow(self, state: WorkflowState, max_attempts: int) -> WorkflowState: ...
    def get_workflow(self, task_id: str) -> WorkflowState | None: ...
    def save_workflow(self, state: WorkflowState, expected_version: int) -> WorkflowState: ...
    def enqueue(self, task_id: str, max_attempts: int, payload: dict[str, Any] | None = None) -> int | str: ...
    def claim(self, worker_id: str, lease_seconds: int) -> QueueDelivery | None: ...
    def extend_lease(self, delivery: QueueDelivery, lease_seconds: int) -> None: ...
    def acknowledge(self, delivery_id: int | str) -> None: ...
    def retry_or_dead_letter(self, delivery: QueueDelivery, error: str, base_delay_seconds: float = 1.0) -> bool: ...
    def record_event(self, task_id: str, event_type: str, payload: dict[str, Any] | None = None) -> None: ...
    def list_events(self, task_id: str) -> list[EventRecord]: ...
    def arguments_hash(self, arguments: dict[str, Any]) -> str: ...
    def get_tool_result(self, idempotency_key: str, arguments: dict[str, Any]) -> dict[str, Any] | None: ...
    def save_tool_result(self, key: str, task_id: str, tool: str, arguments: dict[str, Any], result: dict[str, Any]) -> None: ...
    def create_approval(self, task_id: str, action_id: str) -> None: ...
    def resolve_approval(self, task_id: str, action_id: str, approved: bool, actor: str, reason: str | None) -> None: ...
    def approval_status(self, task_id: str, action_id: str) -> str | None: ...
    def queue_counts(self) -> dict[str, int]: ...
